name: fostershare
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: "1.8.0"

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter

  # Auth
  amplify_flutter: '^0.1.0'
  amplify_auth_cognito: '^0.1.0'

  # SVG 
  flutter_svg: ^0.22.0

  # Input Formmater
  mask_text_input_formatter: ^2.0.0

  # Animations
  animations: ^2.0.0

  # Flutter switch
  flutter_switch: ^0.3.0

  # Toasts CLEANUP
  fluttertoast: ^8.0.3
  oktoast: ^3.0.0

  # Url Launcher
  url_launcher: ^6.0.2

  table_calendar: ^3.0.0

  intl: ^0.17.0

  add_2_calendar: ^2.1.0

  # Share
  share_plus: ^2.0.0

  # GraphQL
  graphql: ^4.0.1
  gql: ^0.12.4

  # Email Validator
  email_validator: ^2.0.1

  firebase_analytics: ^7.0.0

  # TODO REMOVE
  # device_preview: ^0.6.0-beta
  dotted_border: ^2.0.0

  image_picker: ^0.6.7

  # AutoSize text
  auto_size_text: ^2.1.0
  
  # Service Locator
  get_it: ^6.0.0 # has Null Safe

  # State Management
  stacked: ^1.7.7

  # Firebase
  firebase_core: ^0.7.0

  # Push Notifications
  firebase_messaging: ^8.0.0-dev.13

  # Local Notifications
  flutter_local_notifications: ^3.0.0

  # Key-Value Local Database
  hive: ^1.3.0
  hive_flutter: ^0.3.1

  # Json Serialization
  json_serializable: ^3.5.1

  # Navigation
  auto_route: ^0.6.9

  # Pin Code
  pin_code_fields: ^7.0.0

  # Package Info
  package_info: ^0.4.3+4

  # Logger
  logger: ^1.0.0
  sentry_flutter: ^4.0.1

  # Static Analysis
  meta: ^1.2.4

  # Font
  google_fonts: ^1.1.1

  # Page Indicator
  smooth_page_indicator: ^0.2.0

  # Hooks
  flutter_hooks: ^0.16.0
  
  path_provider:

  path:

  webview_flutter:
  flutter_speed_dial: ^3.0.5
  # Mocking
  # mockito: ^4.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^0.6.9
  build_runner: ^1.11.0
  hive_generator: ^0.8.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/svg/emoticons/
    - assets/images/svg/incidents/

  fonts:
  - family: AppIcons
    fonts:
      - asset: assets/fonts/icons/AppIcons.ttf

flutter_intl:
  enabled: true
  class_name: AppLocalizations
  arb_dir: lib/core/localization/langs
  template-arb-file: intl_en.arb
  output_dir: lib/core/localization/generated
