/// Flutter icons AppIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcons
///      fonts:
///       - asset: fonts/AppIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcons';

  static const IconData add = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData bell = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData chevronRight = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData chevronLeft = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData home = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData homeOutlined = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData books = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData booksOutlined = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData userOutlined = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData history = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData historyOutlined =
      IconData(0xe80e, fontFamily: _kFontFam);
}
