export default {  
    miracle_logo_blue: require('../assets/logos/miracle_md_blue.png'),
    miracle_logo_white: require('../assets/logos/miracle_white.png'),
    miracle_logo: require('../assets/logos/logo.png'),
    childImagePlaceholder: require('../assets/logos/no_image_placeholder.png'),
    familAndSocialRelationIcon : require('../assets/icons/family_social_relationships_icon.png'),
    householdEconomyIcon : require('../assets/icons/household_economy_icon.png'),
    livingConditionIcon : require('../assets/icons/living_conditions_icon.png'),
    educationIcon : require('../assets/icons/education_icon.png'),
    healthAndMentalHealthIcon : require('../assets/icons/health_mental_health_icon.png'),
    paperwork : require('../assets/icons/paperwork.png'),
    userIconDefault : require('../assets/icons/userIconDefault.png'),
    Miracle_Verticle_logo : require('../assets/logos/Miracle_Verticle_logo.png'),
    new_assessment_icon : require('../assets/icons/new_assessment_icon.png'),
    incomplete_assessment_icon : require('../assets/icons/incomplete_assessment_icon.png'),
    overdue_assessment_icon : require('../assets/icons/overdue_assessment_icon.png'),
    complete_assessment_icon : require('../assets/icons/complete_assessment_icon.png'),
    upload_assessment_icon : require('../assets/icons/upload_assessment_icon.png'),
    loading_appIcon : require('../assets/logos/loading_appIcon.png'),
};